#!/usr/bin/env python3
"""Generate Codex role configs and skill UI metadata from the maintained catalog."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generated_files():
    catalog = json.loads((ROOT / "catalog.json").read_text(encoding="utf-8"))
    for role in catalog["roles"]:
        skill = role["skill"]
        name = skill.replace("-", "_")
        instructions = (
            f"You are the {role['title']} for the assigned task. "
            f"Use the ${skill} skill: locate its SKILL.md in the available skills and read it before working. "
            "If the companion skill is unavailable, report the missing installation to the parent or user "
            "instead of pretending to have loaded it.\n"
            "Follow applicable project instructions and the requested scope. "
            "Honor assigned file ownership and dependencies. Distinguish analysis or review requests "
            "from requests to make changes. Preserve existing work. "
            "Use tools actually available in this session and report checks honestly.\n"
        )
        if skill != "sdlc-manager":
            instructions += (
                "Complete your bounded assignment and return changes or findings with file references, "
                "verification results, and remaining blockers. Let the parent coordinate other specialists; "
                "do not recursively start another team unless asked to delegate a specific independent subtask.\n"
            )
        else:
            instructions += (
                "Keep overall coordination in the current session. Delegate useful independent work to "
                "specialists, not to another manager. Inspect returned evidence and integrate the result.\n"
            )
        # JSON quoted strings are valid TOML basic strings and YAML scalar strings.
        agent = (
            "# Generated by scripts/build.py; edit catalog.json and skills instead.\n"
            f"name = {json.dumps(name)}\n"
            f"description = {json.dumps(role['summary'])}\n"
            f"developer_instructions = {json.dumps(instructions)}\n"
        )
        ui = (
            "interface:\n"
            f"  display_name: {json.dumps(role['title'])}\n"
            f"  short_description: {json.dumps(role['summary'])}\n"
            f"  default_prompt: {json.dumps(role['prompt'])}\n"
        )
        yield ROOT / "agents" / f"{name}.toml", agent
        yield ROOT / "skills" / skill / "agents" / "openai.yaml", ui


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without writing files")
    args = parser.parse_args()
    stale = []
    for path, content in generated_files():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        parser.exit(1, "Stale generated files:\n" + "\n".join(stale) + "\n")
    print("Generated files are current." if args.check else "Generated 19 agents and 19 skill metadata files.")


if __name__ == "__main__":
    main()
